databases:
    - name: oneecoin-explorer-database
      databaseName: oneecoin
      region: singapore
      plan: free
      user: oneecoin

services:
    - type: web
      name: oneecoin-explorer-server
      region: singapore
      plan: free
      env: python
      buildCommand: "./build.sh"
      startCommand: "gunicorn config.wsgi:application"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: oneecoin-explorer-database
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
          - key: PYTHON_VERSION
            value: 3.9.15
