databases:
    - name: oneecoin
      databaseName: oneecoin
      user: oneecoin

services:
    - type: web
      name: oneecoin
      env: python
      buildCommand: "./build.sh"
      startCommand: "gunicorn config.wsgi:application"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: oneecoin
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
