# Generated by Django 4.1 on 2023-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key_hash", models.BinaryField(max_length=64)),
                ("public_key", models.CharField(max_length=128)),
                ("encrypted_private_key", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
